Repository oracle/javavscode, pull requests merged in 2024-09, with the labels that each got.

#245 Fix for delete cache error on windows
  vscode/src/constants.ts
  vscode/src/extension.ts
Labels: OCA Verified

#257 Backport NB patch for Gradle tooling 8.10 upgrade
  build.xml
  patches/7690.diff
Labels: OCA Verified, Apache-Netbeans, dependencies

#251 Restrict parent directory traversal for finding the associated project
  build.xml
  patches/7722.diff
  vscode/package.json
  vscode/package.nls.json
  vscode/src/extension.ts
  vscode/src/nbcode.ts
Labels: OCA Verified

#260 Revert nb23-rc2
  .github/workflows/main.yml
  BUILD.md
  build.xml
  nbcode/branding/modules/org-netbeans-modules-java-testrunner.jar/org/netbeans/modules/java/testrunner/Bundle.properties
  nbcode/integration/src/org/netbeans/modules/nbcode/integration/layer.xml
  nbcode/integration/src/org/netbeans/modules/nbcode/integration/maven-actions-override.xml
  patches/7001.diff
  patches/7271.diff
  patches/7353.diff
  patches/7368.diff
  patches/7370.diff
  patches/7382.diff
  patches/7390.diff
  patches/7491-preliminary.diff
  patches/7497.diff
  patches/7548_source-1.8.diff
  patches/7583_source-1.8.diff
  patches/7621.diff
  patches/7670.diff
  patches/7733.diff
  patches/remove-db.diff
  vscode/package-lock.json
  vscode/src/extension.ts
Labels: OCA Verified

#248 Refactored JDK Downloader
  THIRD_PARTY_LICENSES.txt
  vscode/l10n/bundle.l10n.en.json
  vscode/l10n/bundle.l10n.ja.json
  vscode/l10n/bundle.l10n.zh-cn.json
  vscode/package-lock.json
  vscode/package.json
  vscode/src/constants.ts
  vscode/src/extension.ts
  vscode/src/jdkDownloader.ts
  vscode/src/jdkDownloader/action.ts
  vscode/src/jdkDownloader/styles.ts
  vscode/src/jdkDownloader/view.ts
  vscode/src/utils.ts
Labels: OCA Verified

#263 Remove redudant images
  vscode/images/SourceCodeFormatter.png
  vscode/images/cloud-explorer.png
  vscode/images/database-explorer.png
Labels: OCA Verified

#252 Fix build script and tests for windows platform
  build.xml
  patches/7271.diff
  vscode/package.json
  vscode/src/test/runTest.ts
  vscode/src/test/suite/general/explorer.test.ts
  vscode/src/test/suite/general/extension.test.ts
  vscode/src/test/suite/gradle/extension.test.ts
  vscode/src/test/testutils.ts
Labels: OCA Verified

#262 Patch for unwanted imports bug from NB
  build.xml
  patches/7699.diff
Labels: OCA Verified

#261 Patch for renaming comments bug
  build.xml
  patches/7724.diff
Labels: OCA Verified

#265 [JAVSCODE-253] adding/updating few language keys and some minor corrections
  vscode/l10n/bundle.l10n.en.json
  vscode/src/extension.ts
Labels: OCA Verified

#259 Upgrade to nb-23-rc3
  .github/workflows/main.yml
  BUILD.md
  THIRD_PARTY_LICENSES.txt
  build.xml
  nbcode/branding/modules/org-netbeans-modules-java-testrunner.jar/org/netbeans/modules/java/testrunner/Bundle.properties
  nbcode/integration/src/org/netbeans/modules/nbcode/integration/layer.xml
  nbcode/integration/src/org/netbeans/modules/nbcode/integration/maven-actions-override.xml
  patches/7001.diff
  patches/7271.diff
  patches/7353.diff
  patches/7368.diff
  patches/7370.diff
  patches/7382.diff
  patches/7390.diff
  patches/7491.diff
  patches/7497.diff
  patches/7548_source-1.8.diff
  patches/7583_source-1.8.diff
  patches/7621.diff
  patches/7670.diff
  patches/7690.diff
  patches/7733.diff
  patches/remove-db.diff
  vscode/package-lock.json
  vscode/src/extension.ts
Labels: OCA Verified

#268 Doing some code cleanup and refactoring
  NOTICE
  build.xml
  vscode/src/extension.ts
Labels: OCA Verified

#274 JDK 23 download option added in JDK Downloader
  vscode/src/constants.ts
Labels: OCA Verified

#273 [JAVSCODE-253] enabling nb support for localisation
  .github/workflows/main.yml
  BUILD.md
  THIRD_PARTY_LICENSES.txt
  build.xml
  patches/l10n/adding-ja-and-zh_CN.diff
  vscode/l10n/bundle.l10n.ja.json
  vscode/l10n/bundle.l10n.zh-cn.json
  vscode/package.nls.ja.json
  vscode/package.nls.zh-cn.json
  vscode/src/extension.ts
  vscode/src/localiser.ts
Labels: OCA Verified, do not merge

#275 Merging feature branch - 23.0.0 into main
  .github/workflows/main.yml
  .gitignore
  BUILD.md
  NOTICE
  README.md
  THIRD_PARTY_LICENSES.txt
  build.xml
  nbcode/branding/modules/org-netbeans-modules-java-testrunner.jar/org/netbeans/modules/java/testrunner/Bundle.properties
  nbcode/integration/nbproject/project.xml
  nbcode/integration/src/org/netbeans/modules/nbcode/integration/LspJavaPlatformProviderOverride.java
  nbcode/integration/src/org/netbeans/modules/nbcode/integration/layer.xml
  nbcode/integration/src/org/netbeans/modules/nbcode/integration/maven-actions-override.xml
  patches/7001.diff
  patches/7271.diff
  patches/7353.diff
  patches/7368.diff
  patches/7370.diff
  patches/7382.diff
  patches/7491.diff
  patches/7548_source-1.8.diff
  patches/7583_source-1.8.diff
  patches/7621.diff
  patches/7670.diff
  patches/7699.diff
  patches/7722.diff
  patches/7724.diff
  patches/7733.diff
  patches/l10n-liscence.diff
  patches/l10n/adding-ja-and-zh_CN.diff
  patches/remove-db.diff
  vscode/README.md
  vscode/images/SourceCodeFormatter.png
  vscode/images/cloud-explorer.png
  vscode/images/database-explorer.png
  vscode/l10n/bundle.l10n.en.json
  vscode/l10n/bundle.l10n.ja.json
  vscode/l10n/bundle.l10n.zh-cn.json
  vscode/package-lock.json
  vscode/package.json
  vscode/package.nls.ja.json
  vscode/package.nls.json
  vscode/package.nls.zh-cn.json
  vscode/src/constants.ts
  vscode/src/explorer.ts
  vscode/src/extension.ts
  vscode/src/jdkDownloader.ts
  vscode/src/jdkDownloader/action.ts
  vscode/src/jdkDownloader/styles.ts
  vscode/src/jdkDownloader/view.ts
  vscode/src/launchConfigurations.ts
  vscode/src/localiser.ts
  vscode/src/nbcode.ts
  vscode/src/runConfiguration.ts
  vscode/src/utils.ts
Labels: OCA Verified

#276 Add copyrights in missing places
  vscode/src/jdkDownloader/action.ts
  vscode/src/jdkDownloader/styles.ts
  vscode/src/jdkDownloader/view.ts
  vscode/src/localiser.ts
Labels: OCA Verified

#270 Known Issue added to README - Enable Preview Maven bug
  README.md
Labels: OCA Verified

#278 Created sbom_generation.yaml file
  sbom_generation.yaml
Labels: OCA Verified

#281 Update jdk in github workflows config
  .github/workflows/main.yml
Labels: OCA Verified

#282 [JVSC-253] Refactor Netbeans localisation build
  .gitignore
  build.xml
  nbcode/l10n/locale_ja/build.xml
  nbcode/l10n/locale_ja/manifest.mf
  nbcode/l10n/locale_ja/nbproject/build-impl.xml
  nbcode/l10n/locale_ja/nbproject/platform.properties
  nbcode/l10n/locale_ja/nbproject/project.properties
  nbcode/l10n/locale_ja/nbproject/project.xml
  nbcode/l10n/locale_ja/src/org/apache/netbeans/l10n/ja/Bundle.properties
  nbcode/l10n/locale_zh_CN/build.xml
  nbcode/l10n/locale_zh_CN/manifest.mf
  nbcode/l10n/locale_zh_CN/nbproject/build-impl.xml
  nbcode/l10n/locale_zh_CN/nbproject/platform.properties
  nbcode/l10n/locale_zh_CN/nbproject/project.properties
  nbcode/l10n/locale_zh_CN/nbproject/project.xml
  nbcode/l10n/locale_zh_CN/src/org/apache/netbeans/l10n/zh_CN/Bundle.properties
  nbcode/nbproject/platform.properties
  patches/l10n-licence.diff
  patches/l10n/adding-ja-and-zh_CN.diff
  patches/l10n/adding-java.lsp.server-ja-and-zh_CN.diff
  patches/l10n/filter-enabled-clusters-disabled-modules-code-cleanup.diff
Labels: OCA Verified

#285 Fixed typos in using l10n for localisation is typescript code and removed unused labels from bundles
  vscode/l10n/bundle.l10n.en.json
  vscode/l10n/bundle.l10n.ja.json
  vscode/l10n/bundle.l10n.zh-cn.json
  vscode/package.nls.json
  vscode/src/extension.ts
Labels: OCA Verified
